// APPLICABILITY: Similar purpose with factory pattern, but in a more deliberate
// and user-input-dependent manner. Precisely

/**
* The abstract class, RaceTemplate, provides a template for the
* attributes of each race subclass.
*
* @author  Lloyd Dela Cruz
* @version 1.0
* @since   2021-12
*/
public abstract class RaceTemplate{
     /**
    * This abstract method is the template for the
    * name of the subclass races
    * 
    * @return String This returns the lowercase name of the race.
    */
    abstract String raceName();

    /**
    * This abstract method is the template for the
    * color of the subclass races
    * 
    * @return String This returns the lowercase color of the race.
    */
    abstract String raceColor();

   /**
   * This method outputs the expected general
   * painting that will be generated by the program
   * using the raceColor and raceName attribute
   * of the user-chosen race.
   * 
   * @return Nothing.
   */
    public final void statusUpdate(){
        System.out.println("Picasso is painting a " + raceColor() + "-skinned " + raceName() + "...");
    }
}
